services:
    _defaults:
        autowire: true
        autoconfigure: true

    SybaseConnector\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/SybaseConnectorBundle.php'
